import type { Metadata } from "next";
import { Suspense } from "react";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Loading from "./loading";
import NextAuthProvider from "@/providers/NextAuthProvider";
import ReduxProvider from "@/redux/ReduxProvider"; 
import Navbar from "@/components/Navbar";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
// src/app/layout.tsx
import { Playfair_Display, Inter } from "next/font/google"; // เปลี่ยนจาก Geist เป็นคู่นี้

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${playfair.variable} ${inter.variable} h-full antialiased`}>
      <body className="font-inter"> {/* กำหนดฟอนต์หลักเป็น Inter */}
        <NextAuthProvider>
          <ReduxProvider>
            <Navbar />
            <Suspense fallback={<Loading />}>
            {children}
            </Suspense>
          </ReduxProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
